### ISSUE TITLE
Support 1.19.4 (infinite effects)

### ISSUE THREAD

**Issue by jbb01** [magicus/statuseffecttimer#14]
Minecraft 1.19.4 added infinite effects. Infinite effects are currently displayed with a zero in the overlay.

**Comment by magicus** [comment]
Thanks for the bug report. Adding 1.19.4 support is on my todo-list.

**Comment by sternschnaube** [comment]
Hello @magicus, any update on this?

**Comment by magicus** [comment]
Sorry for the long delay.

Fixed in ad35b8ac0bd2676744abe1a30c8fb912645f36de.
