### ISSUE TITLE
Feature Request: Scaling option

### ISSUE THREAD

**Issue by sternschnaube** [magicus/statuseffecttimer#15]
I would love to scale the hud elements to '0.5'.

**Comment by magicus** [comment]
Thank you for your taking the time to make a feature request.

What you are suggesting would go against the design principles of this mod, which is "no configs, minimalistic vanilla fix". I will not implement any such functionality.

However, if you install a separate mod to scale the hud elements, Status Effect Timers should work properly with it. If not, that will be considered a bug.
