### ISSUE TITLE
statuseffecttimer is incompatible with the "slight gui modifications" mod

### ISSUE THREAD

**Issue by wrhamxyz** [magicus/statuseffecttimer#3]
I'm using the latest version, the mod shows up on modmenu, and i'm pretty sure there's no error on the log, yet this mod still doesn't change anything, as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/88493761/129323648-0aa32d4d-064c-4a7f-890c-5d63b63deb4c.png)

**Comment by magicus** [comment]
That's weird. I made a quick sanity check to make sure it looked alright at 1.17.1 before releasing. I'll check again.

In the meantime, are you using any other mods that might conflict with statuseffecttimer? @warofzen

**Comment by magicus** [comment]
I have now reconfirmed that it does work for me on 1.17.1. Do you have any other mods loaded? If so, do statuseffecttimer work if you remove all other mods?

If it is a mod conflict, I want to resolve it, but I need to figure out which mod it's conflicting with.

**Comment by warofzen** [comment]
I did use a lot of mods, [here's the complete modlist](https://user-images.githubusercontent.com/88493761/129733088-939424d6-a01b-46e7-9eb8-5f6548bb1bf8.png), there's some mods that modify the hud like bears armor hud and better mount hud and i've tried to disable them but the mod still doesn't work. The mod does work when I disable all the mods but statuseffecttimer.

**Comment by warofzen** [comment]
I think i found the problem. This mod is conflicting with [slight gui modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications), This mod doesn't work if `fluidStatusEffects` from their config is enabled

**Comment by magicus** [comment]
Thank you for the analysis! I'll have a look at Slight gui modifications, and see what the best way to resolve the conflict is.

**Comment by magicus** [comment]
The code that we conflict with (marked "f*ck mod compatibility") is here: https://github.com/shedaniel/slight-gui-modifications/blob/b79f4f6d931b0b22cf6ea011a8e7d17c68a5a3e8/src/main/java/me/shedaniel/slightguimodifications/mixin/MixinGui.java#L60

Unfortunately I don't think there is any way we can interoperate with this. :-( I should try to detect the clash, though, and warn about it, if possible...

**Comment by magicus** [comment]
I have now updated the README with information about the known incompatibility.
