### ISSUE TITLE
Maybe Adding Effect Level to the Icons as Well?

### ISSUE THREAD

**Issue by IJustWantANamePlease** [magicus/statuseffecttimer#5]
It would be nice to have the level of effect displayed on the effect icon.

**Comment by magicus** [comment]
@IJustWantANamePlease Thanks for your suggestion!

This was actually already implemented by https://github.com/magicus/statuseffecttimer/pull/4. However, I have not had the time before to create a new release with this change. 

This is now done. 1.1.0 is out, and supports display of effect level/amplification.
