### ISSUE TITLE
Ability to change effect icon location?

### ISSUE THREAD

**Issue by Boolyman** [magicus/statuseffecttimer#7]
I can't find a mod that changes the location of the effects to the left or top of the screen instead of the right corner.  Is that a functionality you could possibly add?  If so, I would like to use your mod in my upcoming pack.

**Comment by IJustWantANamePlease** [comment]
From the ones I know, Inventory HUD+ and Kron HUD both have this function. They change the style of display a lot though.

**Comment by magicus** [comment]
This will not happen. The idea of Status Effect Timer is just to provide an overlay on top of the vanilla icon. "Moving" the icon actually means "prohibit Vanilla from drawing its icon, and instead drawing it ourselves, elsewhere". That is out of scope for this mod. As you say, other mods do this.
