### ISSUE TITLE
Update modrinth page

### ISSUE THREAD

**Issue by SystematicError** [magicus/statuseffecttimer#8]
The project's [modrinth page](https://modrinth.com/mod/statuseffecttimer) currently shows the latest version being 1.17, however, this mod has since then been updated for 1.18.

**Comment by magicus** [comment]
Good point, I forgot about it. I really much prefer modrinth, but the reality is that it only accounts for a few percent of the downloads. :( I should probably integrate their API for automatic updates into gradle...

**Comment by magicus** [comment]
Fixed now. Also promoted the Modrinth link on the Github readme and on Curseforge.
