### ISSUE TITLE
[documentation] Giselbaers's Durability viewer needs to have effect time feature disabled

### ISSUE THREAD

**Issue by DisasterInbound** [magicus/statuseffecttimer#9]
Hello, thank you for making this mod. It is a real time saver to be able to quickly see how long it takes before the status runs out of time.

I'm playing a [One Block datapack](https://ijaminecraft.com/map/oneblock/) and I noticed the status is overlayed on top of another one and is difficult to read. I'm running Minecraft version 1.16.5 with some mods but I'm not using the Slight GUI mod you mentioned.

Here is a screenshot of how it looks. If you need more information let me know.

![2022-01-22_23 02 24](https://user-images.githubusercontent.com/64549167/150667755-6d9df87d-90d3-4193-9e12-7122679ccfaa.png)

**Comment by magicus** [comment]
Thanks for your report! I will look into this. Other mods might interfere, but data packs should not.

**Comment by Phoenix-Starlight** [comment]
It is caused by Giselbaers' Durability Viewer. It has a option to display the duration of an effect which causes this behavior.

**Comment by magicus** [comment]
@DisasterInbound Are you using Giselbaers' Durability Viewer?

**Comment by DisasterInbound** [comment]
Hi @magicus @Phoenix-Starlight thank you for the help. 

I'm using Giselbaers's Durability viewer. It seems I didn't read the full details of that mod and I thought it only gave the durability of weapons.

I went into the mod settings and disabled the effect time feature and it is now working properly. My bad, sorry.

This issue can now be closed.

**Comment by magicus** [comment]
Thanks @DisasterInbound and @Phoenix-Starlight.

I'll repurpose this bug report as a documentation update, to note the incompatibility with Giselbaers's Durability viewer unless you disable the effect time feature.

**Comment by magicus** [comment]
README updated.
